networks:
  web:
    external: true
  lan:
    external: false
    name: lan_${NAME}

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "5173:5173"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    env_file:
      - .env
    networks:
      - web
      - lan
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.entryPoints=websecure
      - traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcan.dev`)
      - traefik.http.routers.${NAME}.tls=true
      - traefik.http.routers.${NAME}.tls.certresolver=myresolver
